# Generated by Django 4.2.10 on 2026-03-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_actividad_fecha_actividad_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='curso',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
