# Generated by Django 4.2.10 on 2026-03-06 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actividades', '0003_actividad_curso_actividad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
