# Generated by Django 6.0.4 on 2026-04-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_actividad_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['fecha', 'hora_inicio']},
        ),
        migrations.AlterModelOptions(
            name='subtarea',
            options={'ordering': ['fecha_objetivo']},
        ),
        migrations.RenameField(
            model_name='subtarea',
            old_name='fecha',
            new_name='fecha_objetivo',
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('examen', 'Examen'), ('quiz', 'Quiz'), ('taller', 'Taller'), ('proyecto', 'Proyecto'), ('otro', 'Otro')], default='taller', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subtarea',
            name='horas',
            field=models.FloatField(),
        ),
    ]
