# Generated by Django 6.0.4 on 2026-04-18 05:30

from django.db import migrations

def crear_perfiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Perfil = apps.get_model('actividades', 'Perfil')

    for user in User.objects.all():
        Perfil.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_perfil'),
    ]

    operations = [
        migrations.RunPython(crear_perfiles),
    ]
