# Generated by Django 4.2.10 on 2026-05-03 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_auto_20260418_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='AvanceSubtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('hecho', 'Hecho'), ('pospuesto', 'Pospuesto'), ('deshacer', 'Deshacer')], max_length=20)),
                ('nota', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='actividades.subtarea')),
            ],
        ),
    ]
